### ISSUE TITLE
File Start throws error when used in EXE

### ISSUE THREAD

**Issue by fuzzy-focus** [fieldrndservices/logger#1]
Setting a control value via invoke node does not work when used as a sub-VI in the EXE as the frontpanel is usually removed.

Fix: replace static VI ref with strictly typed static VI ref and use "Start Asynchronous Call" Vi.

![fix](https://user-images.githubusercontent.com/13691063/62301147-53695d00-b478-11e9-9c0f-67de2c632fc8.png)

**Comment by volks73** [comment]
Thank you for the bug report. I have investigated implementing the solution/fix you provided. In fact, I was almost ready to push an update with your proposed fix when I discovered that the [Start Asynchronous Call](https://zone.ni.com/reference/en-XX/help/371361R-01/glang/start_asynchronous_call/) is only supported back to LabVIEW 2015. This would break compatibility for LabVIEW 2009 to 2014, which the invoke node does support. I would like to avoid breaking compatibility since I know some people are running and developing on versions older than LabVIEW 2015 with this package.

With that said, I do like the proposed fix and would suggest either _not_ running the logging in the background like in the Simple example for your executable, or you can create your own start VI like so:

![Asynchronous Start Example](https://user-images.githubusercontent.com/1915469/62327716-4e5bdc00-b47f-11e9-9117-9f02fa0a6f74.png)

This is essentially the same thing, but you can use it on newer versions of LabVIEW.

**Comment by fuzzy-focus** [comment]
Ah I hadn't considered backwards compatibility.

I will use the solution you suggested in the VI snippet, thanks!
